provider:
  name: faas
  gateway: http://127.0.0.1:8080
  #gateway: http://192.168.99.100:31112

functions:
  blog:
    lang: go
    handler: ./blog
    image: fntlnz/hugo-fn-blog:latest
    environment:
      content_type: "text/html"
      combine_output: "false"
      repository: "https://github.com/fntlnz/fntlnz.wtf.git"
      baseurl: "https://fntlnz.o6s.io/blog"
      #baseurl: "http://192.168.99.100:31112/function/blog"
